### ISSUE TITLE
Wireframing proposal

### ISSUE THREAD

**Issue by catalinac3** [marsamak/surprise#11]
![IMG_20201027_192027](https://user-images.githubusercontent.com/56088689/97345562-7efd1200-188a-11eb-84f7-1eb7576a07b9.jpg)
![IMG_20201027_192035](https://user-images.githubusercontent.com/56088689/97345573-82909900-188a-11eb-9c05-54dd3828f267.jpg)

@marsamak

**Comment by catalinac3** [comment]
@marsamak 
![Uploading IMG_20201027_192027.jpg…]()
![Uploading IMG_20201027_192035.jpg…]()

**Comment by catalinac3** [comment]
![Uploading IMG_20201027_192027.jpg…]()

**Comment by catalinac3** [comment]
![IMG_20201027_192035](https://user-images.githubusercontent.com/56088689/97345300-2af22d80-188a-11eb-9d87-25d99e355c10.jpg)

**Comment by marsamak** [comment]
> ![IMG_20201027_192027](https://user-images.githubusercontent.com/56088689/97345562-7efd1200-188a-11eb-84f7-1eb7576a07b9.jpg)
> ![IMG_20201027_192035](https://user-images.githubusercontent.com/56088689/97345573-82909900-188a-11eb-9c05-54dd3828f267.jpg)
> 
> @marsamak

Looks good, I'll try to implement this using Flexboxes or Grid along with caching the recipes. BTW actually the API gives always the same 10 recipes, they don't change from call to call.

**Comment by catalinac3** [comment]
yes it is in the comments or I though it was 10 , and a  max of 100. Flex or grid is ok in boxes, with a overflow :auto; to have the ingredients not display and occupied all the page...

**Comment by catalinac3** [comment]
I think a grid would work better in this case, especially if we display 10 recipes. Using the fr for the leftover space of the last line.  I also think the grid is a new issue, so the catching is a feature, has a pull request and the grid is another.
